---
driver:
  name: docker

platforms:
  - name: centos
    driver_config:
      image: geerlingguy/docker-centos7-ansible
      platform: centos
      require_chef_omnibus: false # don't install chef in containers
      use_sudo: true # docker commands use sudo (necessary for local socket)

  - name: debian
    driver_config:
      image: geerlingguy/docker-debian9-ansible
      platform: debian
      require_chef_omnibus: false # don't install chef in containers
      use_sudo: true # docker commands use sudo (necessary for local socket)

        
provisioner:
  name: ansible_playbook
  hosts: test-kitchen    # add 'test-kitchen' host in inventory file
  require_chef_for_busser: false # don't install Chef for Busser tests
  #playbook: default.yml # playbook in root directory

verifier:
  name: inspec
  sudo: false
  
suites:
  - name: hello-doc-ng.install
    # run_list:
    #   - default.yml
    ## Defaults
    # verifier:
    #   inspec_tests:
    #     - test/integration/hello-doc-ng.install
    # attributes:
  # - name: nginx
    # run_list:
    #   - nginx.yml
    # verifier:
    #   inspec_tests:
    #     - test/integration/nginx
    # attributes:
