---
driver:
  # name: dokken
  name: docker

platforms:
  - name: centos-7
    driver_config:
      #image: geerlingguy/docker-centos7-ansible
      platform: centos
      require_chef_omnibus: false # don't install chef in containers
      use_sudo: true # docker commands use sudo (necessary for local socket)
      run_command: /usr/lib/systemd/systemd
      privileged: true
      # use random forwarded port
      forward: 80
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
      
  - name: debian-9
    driver_config:
      image: geerlingguy/docker-debian9-ansible
      platform: debian
      require_chef_omnibus: false # don't install chef in containers
      use_sudo: true # docker commands use sudo (necessary for local socket)
      run_command: /bin/systemd
      privileged: true
      forward: 80
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        
provisioner:
  name: ansible_playbook
  hosts: test-kitchen    # add 'test-kitchen' host in inventory file
  require_chef_for_busser: false # don't install Chef for Busser tests
  ansible_verbose: true
  #playbook: default.yml # playbook in root directory

verifier:
  name: inspec
  sudo: false
  
suites:
  # One instance = test one role (or several if they are dependent)
  # - name: hello-doc-ng.prerequisites
  # # with dependencies: hello-doc-ng.prerequisites in meta/main.yml f
  # for hello-doc-ng.install
  # We can run these two roles under **one** instance
  # - name: hello-doc-ng.install

  # One instance = that test several roles
  - name: hello-doc-ng.install
    provisionner:
      # this playbook call two roles
      playbook: test/integration/hello-doc-ng.install/all.yml
    # run_list:
    #   - default.yml
    ## Defaults
    # verifier:
    #   inspec_tests:
    #     - test/integration/hello-doc-ng.install
    # attributes:
  # - name: nginx
    # run_list:
    #   - nginx.yml
    # verifier:
    #   inspec_tests:
    #     - test/integration/nginx
    # attributes:
