---
- name: add hello-doc-ng public key
  apt_key:
    url: https://nqb1.gitlab.io/hello-doc-ng/GPG_PUBLIC_KEY
    id: 6ABB81CA607AB4E1DF1DA8EF30EDD7E69E6ED82C

- name: install hello-doc-ng repo from gitlab pages
  template:
    src: hello-doc-ng.j2
    dest: "{{ apt_sources_dir }}/hello-doc-ng.list"

# to take new key and repo(s) into account
- name: install apache and hello-doc-ng from repo
  apt:
    name: "{{ deb_pkgs }}"
    update_cache: yes
    state: latest